export const ActionTypes = {
    GLOBAL_LOADING: 'GLOBAL_LOADING',
    GLOBAL_ERROR: 'GLOBAL_ERROR',
    CLEAR_GLOBAL_ERROR: 'CLEAR_GLOBAL_ERROR',
    POST_SIGNUP: 'POST_SIGNUP',
    POST_SIGNIN: 'POST_SIGNIN',
    GET_USER: 'GET_USER',
    GET_USERS: 'GET_USERS',
    DELETE_USER: 'DELETE_USER',
    LOGOUT: 'LOGOUT',     
};